"""Criação inicial da tabela Usuario

Revision ID: 404288e4010f
Revises: 
Create Date: 2025-11-04 23:40:29.769910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404288e4010f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Usuario')
    # ### end Alembic commands ###
