"""Adiciona coluna data_nascimento e aumenta username

Revision ID: e62b183dfb3a
Revises: 404288e4010f
Create Date: 2025-11-04 23:47:29.785674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e62b183dfb3a'
down_revision = '404288e4010f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('senha', sa.String(length=256), nullable=False))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_unique_constraint(None, ['nome'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.drop_column('senha')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
